set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR cortex-m4)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
cmake_policy(SET CMP0123 NEW)

set(ARMCLANG_ROOT "C:/Users/xuqianjx/AppData/Local/Keil_v5/ARM/ARMCLANG" CACHE PATH "Arm Compiler 6 root")
set(ARMCLANG_BIN "${ARMCLANG_ROOT}/bin")

set(CMAKE_C_COMPILER "${ARMCLANG_BIN}/armclang.exe" CACHE FILEPATH "C compiler" FORCE)
set(CMAKE_ASM_COMPILER "${ARMCLANG_BIN}/armasm.exe" CACHE FILEPATH "ASM compiler" FORCE)
set(CMAKE_LINKER "${ARMCLANG_BIN}/armlink.exe" CACHE FILEPATH "linker" FORCE)
set(CMAKE_OBJCOPY "${ARMCLANG_BIN}/fromelf.exe" CACHE FILEPATH "fromelf" FORCE)

set(CMAKE_EXECUTABLE_SUFFIX_C ".axf")
set(CMAKE_EXECUTABLE_SUFFIX_ASM ".axf")

set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> --output <TARGET>")
set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> --output <TARGET>")