set(APP_SOURCES
  Core/Src/main.c
  Core/Src/gpio.c
  Core/Src/freertos.c
  Core/Src/fsmc.c
  Core/Src/stm32f4xx_it.c
  Core/Src/stm32f4xx_hal_msp.c
  Core/Src/stm32f4xx_hal_timebase_tim.c
  Core/Src/system_stm32f4xx.c
  FATFS/Target/bsp_driver_sram.c
  FATFS/Target/sram_diskio.c
  FATFS/App/fatfs.c
  LIBJPEG/App/libjpeg.c
  LIBJPEG/Target/jdata_conf.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_fsmc.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nor.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sram.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_nand.c
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pccard.c
  Middlewares/Third_Party/FatFs/src/diskio.c
  Middlewares/Third_Party/FatFs/src/ff.c
  Middlewares/Third_Party/FatFs/src/ff_gen_drv.c
  Middlewares/Third_Party/FatFs/src/option/syscall.c
  Middlewares/Third_Party/FreeRTOS/Source/croutine.c
  Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
  Middlewares/Third_Party/FreeRTOS/Source/list.c
  Middlewares/Third_Party/FreeRTOS/Source/queue.c
  Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
  Middlewares/Third_Party/FreeRTOS/Source/tasks.c
  Middlewares/Third_Party/FreeRTOS/Source/timers.c
  Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c
  Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
  Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F/port.c
  Middlewares/Third_Party/LibJPEG/source/jcapimin.c
  Middlewares/Third_Party/LibJPEG/source/jcapistd.c
  Middlewares/Third_Party/LibJPEG/source/jdapimin.c
  Middlewares/Third_Party/LibJPEG/source/jdapistd.c
  Middlewares/Third_Party/LibJPEG/source/jcomapi.c
  Middlewares/Third_Party/LibJPEG/source/jcparam.c
  Middlewares/Third_Party/LibJPEG/source/jctrans.c
  Middlewares/Third_Party/LibJPEG/source/jdtrans.c
  Middlewares/Third_Party/LibJPEG/source/jcinit.c
  Middlewares/Third_Party/LibJPEG/source/jcmaster.c
  Middlewares/Third_Party/LibJPEG/source/jcmainct.c
  Middlewares/Third_Party/LibJPEG/source/jcprepct.c
  Middlewares/Third_Party/LibJPEG/source/jccoefct.c
  Middlewares/Third_Party/LibJPEG/source/jccolor.c
  Middlewares/Third_Party/LibJPEG/source/jcsample.c
  Middlewares/Third_Party/LibJPEG/source/jcdctmgr.c
  Middlewares/Third_Party/LibJPEG/source/jfdctint.c
  Middlewares/Third_Party/LibJPEG/source/jfdctfst.c
  Middlewares/Third_Party/LibJPEG/source/jfdctflt.c
  Middlewares/Third_Party/LibJPEG/source/jchuff.c
  Middlewares/Third_Party/LibJPEG/source/jcarith.c
  Middlewares/Third_Party/LibJPEG/source/jcmarker.c
  Middlewares/Third_Party/LibJPEG/source/jdatadst.c
  Middlewares/Third_Party/LibJPEG/source/jdmaster.c
  Middlewares/Third_Party/LibJPEG/source/jdinput.c
  Middlewares/Third_Party/LibJPEG/source/jdmainct.c
  Middlewares/Third_Party/LibJPEG/source/jdcoefct.c
  Middlewares/Third_Party/LibJPEG/source/jdpostct.c
  Middlewares/Third_Party/LibJPEG/source/jdmarker.c
  Middlewares/Third_Party/LibJPEG/source/jdhuff.c
  Middlewares/Third_Party/LibJPEG/source/jdarith.c
  Middlewares/Third_Party/LibJPEG/source/jddctmgr.c
  Middlewares/Third_Party/LibJPEG/source/jidctint.c
  Middlewares/Third_Party/LibJPEG/source/jidctfst.c
  Middlewares/Third_Party/LibJPEG/source/jidctflt.c
  Middlewares/Third_Party/LibJPEG/source/jdsample.c
  Middlewares/Third_Party/LibJPEG/source/jdcolor.c
  Middlewares/Third_Party/LibJPEG/source/jdmerge.c
  Middlewares/Third_Party/LibJPEG/source/jquant1.c
  Middlewares/Third_Party/LibJPEG/source/jquant2.c
  Middlewares/Third_Party/LibJPEG/source/jdatasrc.c
  Middlewares/Third_Party/LibJPEG/source/jaricom.c
  Middlewares/Third_Party/LibJPEG/source/jerror.c
  Middlewares/Third_Party/LibJPEG/source/jmemmgr.c
  Middlewares/Third_Party/LibJPEG/source/jutils.c
  Middlewares/Third_Party/LibJPEG/source/jmemnobs.c
  Drivers/BSP/Components/ili9341/ili9341.c
  Drivers/BSP/Components/ili9341/fsmc_8080.c
  Drivers/BSP/Components/ili9341/ili9341_devboard_ref.c
  Drivers/BSP/Components/xpt2046/xpt2046.c
  UI/Core/Src/bsp_stubs.c
  UI/Core/Src/display_drv.c
  UI/Core/Src/tianji_data.c
  UI/Core/Src/tianji_dial.c
  UI/Core/Src/tianji_particles.c
  UI/Core/Src/tianji_ui.c
  UI/Core/Src/tianji_voice.c
  UI/Core/Src/touch_drv.c
  Utilities/Fonts/font8.c
  Utilities/Fonts/font12.c
  Utilities/Fonts/font16.c
  Utilities/Fonts/font20.c
  Utilities/Fonts/font24.c
  Utilities/Log/lcd_log.c
  MDK-ARM/startup_stm32f407xx.s
)